name: C/C++ CI

on:
  push:
    branches: [ "main","benjamin", "etape1", "etape2", "couleur", "coord", "etape5" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install SFML/Graphics.hpp
      run: sudo apt-get install libsfml-dev
    - name: make
      run: make
    
